config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/teacherlogin' => 'sessions#teacher_new'
  post '/teacherlogin' => 'sessions#teacher_create'
  post '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  root 'welcome#index'
  resources :activities
  resources :courses
  resources :schedules
  resources :students_activities
  resources :teachers do
    resources :courses
    resources :activities
  end
  resources :students do
    resources :schedules
    resources :students_activities
  end
  resources :sessions


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :course
    belongs_to :student

    validates :student_id, presence: true
    validates :course_id, presence: true
    validates :semester, presence: true, inclusion: {in: %w(Fall Spring)}
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    before_action :require_login
    def index
        if params[:student_id]
            @student = find_student
            @schedules = @student.schedules
        else
            @schedules = Schedule.all
        end
    end
    
    def new
        @student = find_student
        @schedule = @student.schedules.build
    end
    
    def show
    end
    
    def create        
        @student = find_student
        @schedule = @student.schedules.build(schedule_params)
        @courses = Course.all
        if @schedule.save
            redirect_to student_schedules_path(@student.id)
        else  
            render :new
        end 
    end

    def edit
        @student = find_student
        @schedule = find_schedule
    end

    def update
        @student = find_student
        @schedule = find_schedule
        if @schedule.update(schedule_params)
            redirect_to student_schedules_path(@student.id)
        else
            render :edit
        end
    end

    def destroy
        @student = find_student
        @schedule = find_schedule
        @schedule.destroy
        redirect_to student_schedules_path(@student.id)
    end

    private

    def schedule_params
        params.require(:schedule).permit(:student_id, :course_id, :semester)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<h2>Edit Schedule</h2>
    <%= @schedule.course.name %> - <%= @schedule.course.description %>
    <br>
<%= form_with model: [@student, @schedule] do |form| %>
    <% form.hidden_field :student_id, value: @student.id %>
    <%= form.select :semester, ["Fall", "Spring"] %>
    <br>
    <%= form.submit %>
<% end %>
<br>
<%= link_to "Schedule", student_schedules_path(current_user.id) %><br>
<br>
<%= link_to "Profile", student_path(current_user.id) %><br>
<%= link_to "Home", root_path %>

app/views/schedules/index.html.erb
<h2><%= @student.first_name %> <%= @student.last_name %>'s Schedule</h2>
<br>
<% if @schedules == nil %>
    <h3>No Schedule</h3>
<% else %>
    <ol>
    <% @schedules.each do |t| %>
        <li><strong><%= t.course.name %></strong> - <%= t.course.description %> - <b><%= t.semester %></b> - <i><%= t.course.teacher.first_name %> <%= t.course.teacher.last_name %></i><br>
        <%= button_to "Remove Course", student_schedule_path(t.student_id, t.id), method: :delete, data: {confirm: "Are you sure?"} %>
        <%= link_to "Edit Course", edit_student_schedule_path(t.student_id, t.id) %><br></li>
        <br>
    <% end %>
    </ol>
    <br>
<% end %>
<p><%= link_to "Add New Course", new_student_schedule_path %></p>
<br>
<%= link_to "Profile", student_path(current_user.id) %><br>
<p><%= link_to "Home", root_path %></p>

app/views/schedules/new.html.erb
<h2>Add New Course to Schedule</h2>
<%= form_with model: [@student, @schedule] do |form| %>
    <%= form.collection_select :course_id, Course.order(:name),:id,:name %>
    <% form.hidden_field :student_id, value: @student.id %>
    <br>
    <%= form.select :semester, ["Fall", "Spring"] %>
    <br>
    <%= form.submit "Add Course" %>
<% end %>
<br>
<%= link_to "Schedule", student_schedules_path(current_user.id) %><br>
<br>
<%= link_to "Profile", student_path(current_user.id) %><br>
<%= link_to "Home", root_path %>