config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/teacherlogin' => 'sessions#teacher_new'
  post '/teacherlogin' => 'sessions#teacher_create'
  post '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  root 'welcome#index'
  resources :activities
  resources :courses
  resources :schedules
  resources :students_activities
  resources :teachers do
    resources :courses
    resources :activities
  end
  resources :students do
    resources :schedules
    resources :students_activities
  end
  resources :sessions


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_secure_password
    has_many :courses
    has_many :activities

    validates :username, presence: true, uniqueness: true
    validates :first_name, presence: true

    def self.teacher_courses
        joins(:courses).group('teachers.last_name')
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :require_teacher_login, except:[:index, :new, :create]

    def index
        @teachers = Teacher.teacher_courses
    end
    
    def new
        if !teacher_logged_in?
            @teacher = Teacher.new
        else
            redirect_to root_path
        end
    end

    def show
        @teacher = find_teacher
    end

    def edit
        @teacher = find_teacher
    end
    
    def update
        @teacher = find_teacher
        @teacher.update(teacher_params)
        redirect_to teacher_path(@teacher)
    end

    def create
        @teacher = Teacher.new(teacher_params)

        if @teacher.save && @teacher.access_code == "123456789"
            session[:user_id] = @teacher.id
            session[:teacher] = true
            teacher_logged_in?
            redirect_to teacher_path(@teacher)
        else  
            render :new
        end 
    end 
    
    private
    
    def teacher_params 
        params.require(:teacher).permit(:first_name, :last_name, :username, :password, :password_confirmation, :access_code, :department)
    end 
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<h2>Change Department</h2>
<h3>Your current Department is: <strong><%= @teacher.department %></strong></h3>
<br>
<%= form_with model: @teacher do |form| %>
    <%= form.select(:department, options_for_select(["Mime", "Circus Clown"])) %>
    <br>
    <%= form.submit "Change Department" %>
<% end %>
<br>
<%= link_to 'Profile', teacher_path(current_teacher.id) %><br>
<%= link_to "Home", root_path %>

app/views/teachers/index.html.erb
<h2>Teachers of Chesapeake Clown College</h2>

<% @teachers.each do |t| %>
    <b><%= t.first_name %> <%= t.last_name %></b> - <i><%= t.department %></i>
    <% t.courses.each do |c| %>
        <li><%= c.name %> - <%= c.description %></li>
    <% end %>
    <br>
    <br>
<% end %>

<p><%= link_to "Home", root_path %></p>

app/views/teachers/new.html.erb
<h2>New Teacher Sign Up</h2>
<% if @teacher.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
    <ul>
      <% @teacher.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<%= form_with model: @teacher, local: true do |form| %>
    First Name: <%= form.text_field :first_name %><br>
    <br>
    Last Name: <%= form.text_field :last_name %><br>
    <br>
    Username: <%= form.text_field :username %><br>
    <br>
    Password: <%= form.password_field :password %><br>
    <br>
    Access Code: <%= form.password_field :access_code %> <small>(Code provided by Administration)</small><br>
    <br>
    <%= form.submit %>
<% end %>
<br>
<%= link_to "Home", root_path %>

app/views/teachers/show.html.erb
<h2>Teacher Profile</h2>
<h3>Welcome <%= @teacher.first_name %>,</h3>
<p>Your department is: <strong><%= @teacher.department %></strong><br>
<%= link_to "Change Department", edit_teacher_path(@teacher.id) %></p><br>
<p>Your profile page offers access to the courses yout teach and the activities you lead.  Please click the links below to view and edit your courses or activities.</p>
<br>
<%= link_to "Courses", teacher_courses_path(current_teacher.id) %><br>
<%= link_to "Activities", teacher_activities_path(current_teacher.id) %><br>
<br>
<%= link_to "Home", root_path %><br>
<br>
<%= button_to 'Logout', logout_path %> 