config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/teacherlogin' => 'sessions#teacher_new'
  post '/teacherlogin' => 'sessions#teacher_create'
  post '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  root 'welcome#index'
  resources :activities
  resources :courses
  resources :schedules
  resources :students_activities
  resources :teachers do
    resources :courses
    resources :activities
  end
  resources :students do
    resources :schedules
    resources :students_activities
  end
  resources :sessions


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :student_activities
    has_many :students, through: :student_activities
    belongs_to :teacher

    validates :name, :description, :teacher_id, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :require_teacher_login, except:[:index, :show]
    def index
        if params[:teacher_id]
            @teacher = find_teacher
            @activities = @teacher.activities
        else
            @activities = Activity.all
        end
    end

    def new
        @teacher = find_teacher
        @activity = @teacher.activities.build
    end

    def show
    end

    def create
        @teacher = find_teacher
        @activity = @teacher.activities.build(activity_params)
        if @activity.save
            redirect_to teacher_activities_path(@teacher.id)
        else  
            render :new
        end 

    end

    def edit
        @teacher = find_teacher
        @activity = find_activity
    end

    def update
        @teacher = find_teacher
        @activity = find_activity
        if @activity.update(activity_params)
            redirect_to teacher_activities_path(@teacher.id)
        else  
            render :edit
        end 
    end

    def destroy
        @activity = find_activity
        @activity.destroy
        redirect_to teacher_activities_path(current_teacher.id)
    end

    private

    def activity_params 
        params.require(:activity).permit(:name, :description, :teacher_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h2>Edit Activity Page</h2>
<br>
<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
    <ul>
      <% @activity.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: [@teacher, @activity], local: true do |form| %>
    Activity Name: <%= form.text_field :name %><br>
    <br>
    Activity Description: <%= form.text_area :description, rows: 4, cols: 40 %><br>
    <br>
    <%= form.submit %>
<% end %>
<br>
<%= link_to "Activities", teacher_activities_path(current_teacher.id) %><br>
<br>
<%= link_to 'Profile', teacher_path(current_teacher.id) %><br>
<%= link_to "Home", root_path %>

app/views/activities/index.html.erb
<% if @teacher %>
    <h2><%= @teacher.first_name %> <%= @teacher.last_name %>'s Activities</h2>
<% else %>
    <h2>Activity Listing</h2>
<% end %>

<% if @teacher %>
    <ol>
    <% @activities.each do |t| %>
        <li><strong><%= t.name %></strong> - <%= t.description %> - <i><%= t.teacher.first_name %> <%= t.teacher.last_name %></i><br>
        <%= link_to "Edit Activity", edit_teacher_activity_path(t.teacher_id, t.id) %><br>
        <%= button_to "Delete Activity", teacher_activity_path(t.teacher_id, t.id), method: :delete, data: {confirm: "Are you sure?"} %></li>
        <br>
        <% end %>
    </ol>
    <%= link_to "Create Activity", new_teacher_activity_path %><br>
<% else %>
    <ol>
    <% @activities.each do |t| %>
    <li><strong><%= t.name %></strong> - <%= t.description %> - <i><%= t.teacher.first_name %> <%= t.teacher.last_name %></i><br>
    <br>
    <% end %>
    </ol>
<% end %>
<br>
<% if @teacher %>
<br>
<%= link_to 'Profile', teacher_path(current_teacher.id) %><br>
<% end %>
<p><%= link_to "Home", root_path %></p>

app/views/activities/new.html.erb
<h2>Create New Activity</h2>
<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
    <ul>
      <% @activity.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [@teacher, @activity], local: true do |form| %>
    Activity Name: <%= form.text_field :name %><br>
    <br>
    Activity Description: <%= form.text_area :description, rows: 4, cols: 40 %><br>
    <% form.hidden_field :teacher_id, value: @teacher.id %> 
    <br>
    <%= form.submit %>
<% end %>
<br>

<%= link_to "Activities", teacher_activities_path(current_teacher.id) %><br>
<br>
<%= link_to 'Profile', teacher_path(current_teacher.id) %><br>
<%= link_to "Home", root_path %>